CREATE TABLE relations_articles (
    article_day INT,
    question_number INT,
    category_id VARCHAR(255),
    PRIMARY KEY (article_day, question_number, category_id),
    FOREIGN KEY (article_day, question_number) REFERENCES articles(day, question),
    FOREIGN KEY (category_id) REFERENCES categories(category)
);

INSERT INTO relations_articles (article_day, question_number, category_id)
VALUES  (575,   1,  'object'),
        (575,   1,  'furniture'),
        (575,   2,  'cinema'),
        (575,   2,  'movie'),
        (575,   3,  'geography'),
        (575,   3,  'geography_europe'),
        (575,   3,  'physical_geography'),
        (575,   4,  'people'),
        (575,   4,  'architecture'),
        (575,   5,  'lifestyle'),
        (575,   6,  'people'),
        (575,   6,  'people_internet'),
        (575,   7,  'people'),
        (575,   7,  'politics'),
        (575,   7,  'politician'),
        (575,   8,  'religion_myth'),
        (575,   9,  'object'),
        (575,   10, 'anthropology'),
        (574,   1,  'technology'),
        (574,   2,  'fictional_character'),
        (574,   3,  'literature'),
        (574,   4,  'cinema'),
        (574,   4,  'movie'),
        (574,   5,  'art'),
        (574,   6,  'people'),
        (574,   6,  'religion_myth'),
        (574,   7,  'people'),
        (574,   7,  'music'),
        (574,   8,  'sport'),
        (574,   9,  'technology'),
        (574,   10, 'people'),
        (574,   10, 'art'),
        (574,   10, 'artist');